### ISSUE TITLE
Info Request: Reference to Datalog specification

### ISSUE THREAD

**Issue by RAbraham** [gkastrinis/deepdoop#33]
Hi,
Very cool library. In your docs, you mention

"Input programs are written in a **modern Datalog specification** and can afterwards be compiled to valid forms for the aforementioned Datalog engines"

I was wondering if there is a reference/document which provides a detailed description of such a spec?

Thanks

**Comment by gkastrinis** [comment]
I'm glad that you like the project!

In the past, I had started an attempt to write wiki articles. It is not a finished work but it has some info.
https://github.com/gkastrinis/panda/wiki

Also, you could check the test files on the projects (not the ones that are expected to fail).
`src/test/resources`

But in general, keep in mind that although this is not a discontinued project, currently there is not that much of active development due to outside factors. I do hope that I will continue with this project in the next couple months.

**Comment by RAbraham** [comment]
The wiki is great. Thanks!
